apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: dataset_catalogue #ZGF0YXNldF9zY2hlbWE= # base64 encoded value of 'dataset_schema'
  POSTGRES_USER: fcasadei #ZmNhc2FkZWk= # base64 encoded value of 'fcasadei'
  POSTGRES_PASSWORD: 7IGc540zOTX04ET #bXlwYXNzd29yZA== # base64 encoded value of 'mypassword'
