apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: ZGF0YXNldF9jYXRhbG9ndWU=  #dataset_catalogue #ZGF0YXNldF9zY2hlbWE= # base64 encoded value of 'dataset_schema'
  POSTGRES_USER: ZmNhc2FkZWk= #fcasadei #ZmNhc2FkZWk= # base64 encoded value of 'fcasadei'
  POSTGRES_PASSWORD: N0lHYzU0MHpPVFgwNEVU #7IGc540zOTX04ET #bXlwYXNzd29yZA== # base64 encoded value of 'mypassword'
