apiVersion: v1
kind: Secret
metadata:
  name: data-catalogue-postgres-secret
  namespace: synthema
type: Opaque
stringData:
  POSTGRES_DB: dataset_catalogue
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppassword
  # MinIO credentials (same MinIO the fl-server writes reports to)
  MINIO_ACCESS_KEY: test-ak-thema
  MINIO_SECRET_KEY: test-sk-thema

  KEYCLOAK_PUBLIC_KEY: ""
